noun1 = input("Type a common or proper noun")
verb1 = input("Type a verb with -ing")
place1 = input("Type a place")
randomthing = input("Type a random thing")
verb2 = input("Type an action verb in past tense")
number = input("Type a number")
prison = input("Type a type of prison or prison-like place")
verb3 = input("Type an action verb in past tense")
verb4 = input("Type an action verb in past tense")
print("Once upon a time, not long ago I was a " + noun1 + " and I'm " + verb1 + " it. One day while I was walking down the " + place1 + " and I saw a " + randomthing + " The " + randomthing + " at me and I freaked out and " + verb2 + " it. After " + verb2 + " ing it, the " + randomthing + " fell and died. I was already on my " + number + " strike and I couldn't go back to " + prison + " so I " + verb3 + " my crazy butt out of there and " + verb4 + " all the evidence." )